baseURL = "https://othiagob.github.io/home/"
languageCode = "pt-br"
title = "Blog - Thiago Borghardt"
theme = "archie"
copyright = "© Thiago Borghardt"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
	pagerSize = 5

[params]
	mode = "auto"
	useCDN = false
	subtitle = "Programação backend, tecnologia e aprendizado em Ciência da Computação"
	mainSections = ["posts"]
	summaryLength = 30

[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/othiagob"

[[params.social]]
	name = "LinkedIn"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/thiago-borghardt-5234b0334/"

[[params.social]]
	name = "Email"
	icon = "mail"
	url = "mailto:thiago.backend@gmail.com"

[[params.social]]
	name = "WhatsApp"
	icon = "message-circle"
	url = "https://wa.me/5569993684773"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Posts"
	url = "/posts/"
	weight = 2

[[menu.main]]
	name = "Sobre"
	url = "/about/"
	weight = 3

[[menu.main]]
	name = "Tags"
	url = "/tags/"
	weight = 4

[[menu.main]]
	name = "Buscar"
	url = "/search/"
	weight = 5
